{
  "headers": {
    "authorization": "35246",
    "token": "sdgsg",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.29.0",
    "accept": "*/*",
    "postman-token": "f6fb7680-2b7d-4a8a-8a30-0c997bb91713",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "563"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/employees",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/employees",
  "listenerPath": "/api/*",
  "relativePath": "/api/employees",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/employees",
  "rawRequestPath": "/api/employees",
  "remoteAddress": "/127.0.0.1:56436",
  "requestPath": "/api/employees"
}